### ISSUE TITLE
Publish on conda-forge?

### ISSUE THREAD

**Issue by erikmannerfelt** [mmaelicke/scikit-gstat#103]
Thanks for this great package!

We use `scikit-gstat` in the WIP project [xdem](https://github.com/GlacioHack/xdem) and aim to publish it on conda-forge. With `scikit-gstat` as a required dependency, I wonder if there is any plan to publish this on conda-forge as well?

Thanks in advance,
Erik

**Comment by mmaelicke** [comment]
Hey Erik,
Thanks for your feedback! Yeah, ultimately it should be available on conda-forge. But my plans were not super-short-term. Right now I am still developing on a first stable release `1.0`. I feel like I am almost there and the interfaces should become stable soon. My feeling was that the *stable release 1.0* should be the first one on conda forge.
Right now I am preparing a [GMD](https://www.geoscientific-model-development.net/) publication about this package, which would complement the 1.0 version. 
Right now, I am also a bit too busy to make myself familiar with these conda feedstock procedures. But if you guys need it there, we can definitely discuss possibilities. Maybe @redhog is also interested in having scikit-gstat on conda-forge and would maintain the recipe and feedstock repo as well? 
Do you have any time deadline until scikit-gstat has to be on conda forge?

Thanks and best,
Mirko

**Comment by erikmannerfelt** [comment]
Thanks for your answer! Conda-builds are quite a mess to get started with, but when they work, they are quite easy to maintain. I'm trying to help out over at https://github.com/rock-learning/pytransform3d/issues/134, because that is also a dependency of ours that is not yet on conda-forge.

I'd be delighted to draft a recipe if you like! I am pretty sure one can automate the build using a GitHub Action, so that the future conda-forge version would always be a clone of the pypi version for example.

We are still in early alpha at `xdem`, but most of our Windows users have a bad time installing it with pip, so publishing on conda-forge would be great for both development and adaptation!

**Comment by mmaelicke** [comment]
A first draft would be really helpful! Always easier not to start from zero. 
You can also go forward and open a PR for the recipe and add me as a maintainer if you like to. I guess it would be fine for you if I only occasionally update the feedstock as long as scikit-gstat `<1.0.0`? 
On the other hand you can always go forward and bump the conda forge version if you need to. 
Great, this is nice. Was on my todo for years, but sometimes you need to get pushed...

**Comment by erikmannerfelt** [comment]
I almost got it working on https://github.com/conda-forge/staged-recipes/pull/14998! For some reason, the linux and macOS builds work, but the windows build fails due to dependency conflicts... Really odd! Have you seen this before?

Here's the log with `conda`'s terrible conflict messages:
https://dev.azure.com/conda-forge/84710dde-1620-425b-80d0-4cf5baca359d/_apis/build/builds/320663/logs/23

**Comment by erikmannerfelt** [comment]
It passed the tests! 

I misunderstood the build requirements, so after fixing that, the weird conflicts are gone. I still have no idea where they came from!

**Comment by mmaelicke** [comment]
Nice, thank you very much for your effords! 
Wow, I couldn't even spot the actual error in the log...

If I get the procedures right, the PR is open now and will be merged by the conda-forge team to become available on the channel, right? Or is any further action necessary now?

**Comment by erikmannerfelt** [comment]
`scikit-gstat` is now on conda-forge!

```bash
conda install scikit-gstat
```

Sorry for not answering you before; now we can make PRs to https://github.com/conda-forge/scikit-gstat-feedstock when updating the version.

**Comment by mmaelicke** [comment]
Hey Erik,

Thank you so much for your effort!
