### ISSUE TITLE
Option to omit last bin when maxlag is set

### ISSUE THREAD

**Issue by tnigon** [mmaelicke/scikit-gstat#11]
When using a maxlag value, the last bin in the semivariogram seems to consist of all data with a greater value than maxlag. Therefore, when a model is fit to the binned values of the semivariogram, that last bin value affects the model substantially if it is different from the 2nd to last bin value. I'm not sure this is what is the desired behavior, but if it is, would it make sense to provide an option to the user for fitting the model after omitting the last bin (would only apply when maxlag is set)?

![See a sample semivariogram here](https://user-images.githubusercontent.com/8249296/43803063-5a31353a-9a5d-11e8-8985-54cad0ed354b.png) where maxlag was set and the last bin is at a value of ~600, whereas the 2nd to last bin is at a value close to 1000. Notice the spherical model (green line) shows a sill that is clearly at a value less than those suggested by the points.

**Comment by mmaelicke** [comment]
Dear Tyler,
Thanks for submitting this issue. I am aware of that behaviour and in fact I am reworking most of the code at moment, to solve some issues including this one. There is the dev branch on this repository with the reworked code in it. Some unittests are still failling or missing, but it is work in progress. Once it is stable, I will merge the new version into the master branch and update the pip version.
The dev version does already handle the maxlag value correctly. Moreover, you can now pass a string like 'median', to make the class use the median of all separating distances as a maximum value.
Unfortunately, this comes at the cost of downward compability. The attributes of Variogram class changed a lot. I still have to write down all the changes, but the most important ones are already in the Variogram class docstring. Another thing that I reworked completely is the fitting of the theoretical function. This is now implemented much closer to scipy's curve_fit and least_squares methods, which are in fact used under the hood. Consulting the Variogram class docstring, the Variogram.fit and Variogram.fit_sigma docstring should illustrate how one can now weight the fitting for different lag classes, up to omitting one, if this is still desired.
So maybe just use the dev-branch?
I hope this is helpful and you find your way through the new class. In case you need more explanation, please ask and we can re-open this issue.
Thanks

Mirko

**Comment by mmaelicke** [comment]
BTW, in my working group I wrote [this notebook](https://github.com/KIT-HYD/microstudies/blob/master/fitting/variogram_fitting.ipynb)  as a guideline for our students, how one can fit a theoretical variogram. Most of the stuff is already implemented into the Variogram class. When using 'trf' as fit_method (default now), it will set the bounds and initial guess automatically. The uncertainty of the bins can be set through the fit_sigma attribute, which docstring looks like:



        Set or calculate an array of observation uncertainties aligned to the
        Variogram.bins. These will be used to weight the observations in the
        cost function, which divides the residuals by their uncertainty.

        When setting fit_sigma, the array of uncertainties itself can be
        given, or one of the strings: ['linear', 'exp', 'sqrt', 'sq']. The
        parameters described below refer to the setter of this property.

        Parameters
        ----------
        sigma : string, array
            Sigma can either be an array of discrete uncertainty values,
            which have to align to the Variogram.bins, or of type string.
            Then, the weights for fitting are calculated as a function of
            (lag) distance.

              * sigma='linear': The residuals get weighted by the lag
              distance normalized to the maximum lag distance, denoted as w_n
              * sigma='exp': The residuals get weighted by the function:
              w = e^{1 / w_n}
              * sigma='sqrt': The residuals get weighted by the function:
              w = sqrt(w_n)
              * sigma='sq': The residuals get weighted by the function:
              w = w_n ** 2

        Returns
        -------
        void


        Notes
        -----
        The cost function is defined as:

        .. math::
            chisq = \sum {\frac{r}{\sigma}}^2

        where r are the residuals between the experimental variogram and the
        modeled values for the same lag. Following this function,
        small values will increase the influence of that residual, while a very
        large sigma will cause the observation to be ignored.


Hope, this is helpful for you. 
Best

Mirko

**Comment by mserouar** [comment]
I still have this issue, did you rework on it or is my version old ?

**Comment by mserouar** [comment]
I stil have this issue, did you rework on it, or is my version too old ?

**Comment by mmaelicke** [comment]
Hi,
This issue should be solved. Please make sure your version is updated. I will re-open the issue, so please let me know if updating the version solved the problem. Otherwise, a minimal example to illsutrate the issue would be helpful and appreciated.
Best
Mirko

**Comment by mserouar** [comment]
v 0.2.8 so the latest one, it happened once in a bunch of image, I guess when n_lags was too large for maxlag = 0.5

**Comment by mmaelicke** [comment]
Hi,
I cannot really help if I can't reproduce this behavior. You will need to post a minimal example here to make me understand what is happening.
Thank you,

Mirko

**Comment by mmaelicke** [comment]
I will close this issue due to inactivity.
If you feel like that there is something wrong with scikit-gstat, please provide an example and I will re-open the issue.
