### ISSUE TITLE
Bug in genton estimator

### ISSUE THREAD

**Issue by KentaroAoyama** [mmaelicke/scikit-gstat#129]
I found a bug in the Genton semi-variance estimator, and have sent you a PR.
I hope you will check it out.
PR: https://github.com/mmaelicke/scikit-gstat/pull/128

**Comment by mmaelicke** [comment]
Hey,
Thanks a lot! I will check this out after the weekend.

Best,
Mirko

**Comment by mmaelicke** [comment]
merged with #128 and on PyPI as version `1.0.2`.
Thanks again!
