### ISSUE TITLE
emit warnings for cross-variograms

### ISSUE THREAD

**Issue by mmaelicke** [mmaelicke/scikit-gstat#136]
needed for GSTools interface, as the info about being a cross-variogram gets lost in translation.

**Comment by MuellerSeb** [comment]
Nice new feature! Cross variogram is also on the TODO list for GSTools. Good to have a warning for now.

**Comment by mmaelicke** [comment]
This is implemented, the warning is raised. @MuellerSeb let me know when `CovModel` supports cross variables, then we can look into the interface.
