### ISSUE TITLE
NumbaDeprecationWarning: The 'nopython' default is changing for 'numba.jit'

### ISSUE THREAD

**Issue by snowman2** [mmaelicke/scikit-gstat#146]
skgstat/models.py:23: NumbaDeprecationWarning: The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.

**Comment by mmaelicke** [comment]
this is solved with version `1.0.11`

**Comment by snowman2** [comment]
Thanks @mmaelicke 👍

**Comment by rhugonnet** [comment]
Thanks @mmaelicke! Would be great to release `1.0.11` on conda to solve the warnings there too for dependent packages :)
