### ISSUE TITLE
Support for Spatial-Temporal variograms

### ISSUE THREAD

**Issue by mouyi321** [mmaelicke/scikit-gstat#149]
Respected author,

I have some inquiries regarding the spatiotemporal variograms. I would like to clarify that the implementation I mentioned earlier seems to assume a continuous temporal axis. Specifically, it portrays data as several continuous line in the entire three-dimensional spatiotemporal coordinate system. However, I am interested in working with a completely random distribution of data in this three-dimensional spatiotemporal coordinate system. Therefore, I would like to know if it is feasible to utilize your library for my specific requirements, or if you have any alternative suggestions. I sincerely appreciate your assistance. Thank you.

**Comment by mmaelicke** [comment]
Hi there,

The `SpatioTemporalVariogram` basically treats the temporal axis very similar to the spatial one. That means, the **sample** can be derived at very irregular time steps, just like the spatial axis can be sampled very different from a regular grid. 
The variogram itself, however, is in both cases calculated for residual values, both in space and time. That means, the separating distance and the separating time is relevant. To statistically describe both using a geostatistical model, the point pairs are grouped into lag classes. This is done for the spatial and the temporal axis indenpendently.  So, finally, you end up with a margianal (temporal) model that can be based on irregular samples. 
The method for finding lag classes can be changed, as well. You can refer to the [docs](https://mmaelicke.github.io/scikit-gstat/reference/spacetimevariogram.html), where you find the `xbin` and `tbin` parameters, to change the method for the spatial and temporal lag classes, respectively. The docs are a bit thin, but you can refer to the [normal variogram](https://mmaelicke.github.io/scikit-gstat/reference/variogram.html), where this parameter is called `dist_func`. It also takes discrete values.

I hope this goes into the right direction, about what you are actually asking. If not, please feel free to clarify. Maybe you also have a data sample you could upload. That might make this clearer for me.

Thanks and best,

Mirko

**Comment by mouyi321** [comment]
> Hi there,
> 
> The `SpatioTemporalVariogram` basically treats the temporal axis very similar to the spatial one. That means, the **sample** can be derived at very irregular time steps, just like the spatial axis can be sampled very different from a regular grid. The variogram itself, however, is in both cases calculated for residual values, both in space and time. That means, the separating distance and the separating time is relevant. To statistically describe both using a geostatistical model, the point pairs are grouped into lag classes. This is done for the spatial and the temporal axis indenpendently. So, finally, you end up with a margianal (temporal) model that can be based on irregular samples. The method for finding lag classes can be changed, as well. You can refer to the [docs](https://mmaelicke.github.io/scikit-gstat/reference/spacetimevariogram.html), where you find the `xbin` and `tbin` parameters, to change the method for the spatial and temporal lag classes, respectively. The docs are a bit thin, but you can refer to the [normal variogram](https://mmaelicke.github.io/scikit-gstat/reference/variogram.html), where this parameter is called `dist_func`. It also takes discrete values.
> 
> I hope this goes into the right direction, about what you are actually asking. If not, please feel free to clarify. Maybe you also have a data sample you could upload. That might make this clearer for me.
> 
> Thanks and best,
> 
> Mirko

**Comment by mouyi321** [comment]
Dear author,

I apologize if I didn't describe my question clearly. My data is randomly distributed throughout the [x, y, t] domain. However, I noticed that your implementation allows for arbitrary spatial location [x,y] of sampling points, but there must be values at every moment T. Is my understanding correct?

**Comment by mouyi321** [comment]
Dear author,

I apologize if I didn't describe my question clearly. My data is randomly distributed throughout the [x, y, t] domain. However, I noticed that your implementation allows for arbitrary spatial location [x,y] of sampling points, but there must be values at every moment T. Is my understanding correct?

**Comment by mmaelicke** [comment]
While I am reading your question, I am realizing: that is correct. 
I am actually not sure, how the Variogram will handle NA values in the time series. This is something you could try and report back if it does not work. For the variogram it should be possible to handle NA values, but kriging will not work (which is not supported for spatio-temporal variograms right now, anyway).

I am planning to refactor the spatial-temporal variogram to, among others, include the temporal axis explicitly. I could do this with your question in mind. But please be aware that it will still take a couple of weeks before I can get started.
If you could provide an example, ie. of actual data, that can be really helpful.

Best,
Mirko

**Comment by mouyi321** [comment]
Thank you very much for your reply.

**Comment by mouyi321** [comment]
Thank you very much for your reply.
