### ISSUE TITLE
Bug: skgstat.Variogram: After scipy update from 1.11.1 to 1.11.2: Optimal parameters not found

### ISSUE THREAD

**Issue by ekloberdanz** [mmaelicke/scikit-gstat#161]
After the release of scipy 1.11.2 skgstat.Variogram begun to throw RuntimeError: Optimal parameters not found: The maximum number of function evaluations is exceeded.

**Comment by mmaelicke** [comment]
Thanks for reporting, I am on vacation next week and will look into this right after, as soon as possible.

Best,
Mirko

**Comment by mmaelicke** [comment]
I am struggling to reproduce the error. Can you give me some more info? Do you experience the bug with any kind of parameters, or just a specific instance?
Especially, the exact Python version and maybe upload a csv containing some sample data and a minimal example. 

From the scipy release notes, I can only find one issue that is related to the `scipy.optimize` module (https://github.com/scipy/scipy/issues/18793). Right now, although being relevant for SciKit-GStat, I cannot see how this bugfix could cause the reported error.

Do you by any chance use Python 3.11? I am a bit behind in terms of testing and have neither updated the CI to test against Python 3.11, nor am I using it any of my code pipelines. If so, this might be a good opportunity to catch up.

**Comment by rhugonnet** [comment]
Indeed, a bug was introduced in 1.11.2 when trying to fix https://github.com/scipy/scipy/issues/18793.
They're on it: https://github.com/scipy/scipy/issues/19103

**Comment by rhugonnet** [comment]
Still not fixed for all cases with 1.11.3, as we saw in #160.
I opened an issue with a reproducible example: https://github.com/scipy/scipy/issues/19351

**Comment by rhugonnet** [comment]
This bug has been fixed in SciPy, now works with 1.11.4. We can close!
