### ISSUE TITLE
Formula for γ in the documentation for the Spherical model

### ISSUE THREAD

**Issue by Kenichiro-Yoshimi** [mmaelicke/scikit-gstat#164]
The formula for $\gamma$ in the documentation for the spherical model is as follows:
$\gamma = b + C_0 * (1.5*\frac{h}{a} - 0.5 * \frac{h}{a}^3)$
(https://scikit-gstat.readthedocs.io/en/latest/reference/models.html#spherical-model)

However, I believe the following is correct:
$\gamma = b + C_0 * (1.5*\frac{h}{a} - 0.5 * (\frac{h}{a})^3)$

**Comment by mmaelicke** [comment]
Hey,

Sorry for the late response, I was off for the weekend. Yeah, you are right, the docs are imprecise here. Note, that the actual implementation is as you report. I will fix the docs.
Thanks!
