### ISSUE TITLE
Has Directional Variogram been tested?

### ISSUE THREAD

**Issue by mlees0209** [mmaelicke/scikit-gstat#172]
In the Directional Variogram docs, there is a note that: "The calculation is not performant and not tested yet". This note was added in 2018 and has never been removed. Has the code been tested and can this warning be removed? Else, if the Directional Variogram class really is not performant and is untested, then this should be highlighted at the very top of the docs.

**Comment by mmaelicke** [comment]
Oh yeah, thanks man. The class is not only tested, but has been improved, optimized and re-written in parts since 2018. Thus, I'll take out the note, thanks for pointing out.
