### ISSUE TITLE
Wrong value of "sill" when setting "use_nugget" to true

### ISSUE THREAD

**Issue by IAGO1215** [mmaelicke/scikit-gstat#180]
![image](https://github.com/mmaelicke/scikit-gstat/assets/66477449/6ee7cb5d-bbab-4ea1-8b67-07d337c0ca6a)

The plot is shown above, as we can see that the sill should be near to 0.12. However the output of "parameters" is below: 

![1715162245384](https://github.com/mmaelicke/scikit-gstat/assets/66477449/71b6669f-6299-487e-8874-e8e168896e58)

where the sill is equal to 0.036. 

But when setting "use_nuggt" to false, the value of the sill will be consistent with the plot figure. 

I could provide the data used in case.

**Comment by mmaelicke** [comment]
This could be clearer in the docs, sorry.

The second parameter is the *partial* sill. To get the sill, you need to add the nugget to the partial sill.
