### ISSUE TITLE
Get the values of variogram estimator for given lags

### ISSUE THREAD

**Issue by IAGO1215** [mmaelicke/scikit-gstat#181]
After going through the documentation, I couldn't figure out how to get the values of variogram estimator (Matheron for example) for given lags. There are residuals, RMSE ... functions available so I believe I must have missed sth. 

For example, I would like to get the semivariance value of variogram estimator at the lag equal to the range of the spherical variogram model.

**Comment by mmaelicke** [comment]
Are we talking about the empirical semi-variance value for the lags that contains the effective range or the value modeled by the fitted model at the effective range?

Both is possible, I tried to illustrate both options in the colab below:

https://colab.research.google.com/drive/1rrqkuMOIJWAECtMm-Vm4uw8C06l9IKne?usp=sharing

Let me know if that was helpful.
