### ISSUE TITLE
AttributeError: `np.NaN` was removed in the NumPy 2.0 release. Use `np.nan` instead.

### ISSUE THREAD

**Issue by mothlight** [mmaelicke/scikit-gstat#184]
from skgstat import Variogram

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[2], line 1
----> 1 from skgstat import Variogram
      2 import pandas as pd
      3 import numpy as np

File ~/anaconda3/envs/py3.10.6/lib/python3.12/site-packages/skgstat/__init__.py:1
----> 1 from .Variogram import Variogram
      2 from .DirectionalVariogram import DirectionalVariogram
      3 from .SpaceTimeVariogram import SpaceTimeVariogram

File ~/anaconda3/envs/py3.10.6/lib/python3.12/site-packages/skgstat/Variogram.py:19
     17 from skgstat import plotting
     18 from skgstat.util import shannon_entropy
---> 19 from .MetricSpace import MetricSpace, ProbabalisticMetricSpace
     20 from skgstat.interfaces.gstools import skgstat_to_gstools, skgstat_to_krige
     23 class Variogram(object):

File ~/anaconda3/envs/py3.10.6/lib/python3.12/site-packages/skgstat/MetricSpace.py:10
      6 import numpy as np
      7 import multiprocessing as mp
---> 10 def _sparse_dok_get(m, fill_value=np.NaN):
     11     """Like m.toarray(), but setting empty values to `fill_value`, by
     12     default `np.NaN`, rather than 0.0.
     13 
   (...)
     17     fill_value : float
     18     """
     19     mm = np.full(m.shape, fill_value)

File ~/anaconda3/envs/py3.10.6/lib/python3.12/site-packages/numpy/__init__.py:397, in __getattr__(attr)
    394     raise AttributeError(__former_attrs__[attr])
    396 if attr in __expired_attributes__:
--> 397     raise AttributeError(
    398         f"`np.{attr}` was removed in the NumPy 2.0 release. "
    399         f"{__expired_attributes__[attr]}"
    400     )
    402 if attr == "chararray":
    403     warnings.warn(
    404         "`np.chararray` is deprecated and will be removed from "
    405         "the main namespace in the future. Use an array with a string "
    406         "or bytes dtype instead.", DeprecationWarning, stacklevel=2)

AttributeError: `np.NaN` was removed in the NumPy 2.0 release. Use `np.nan` instead.

Can be fixed by editing 
~/anaconda3/envs/py3.10.6/lib/python3.12/site-packages/skgstat/MetricSpace.py
Change 
def _sparse_dok_get(m, fill_value=np.NaN):
to 
def _sparse_dok_get(m, fill_value=np.nan):

**Comment by mmaelicke** [comment]
Thanks for pointing out! I will release a patch as soon as possible.

**Comment by mmaelicke** [comment]
just fixed with version `1.0.17`
