### ISSUE TITLE
Plotting Kriging interpolation result over map

### ISSUE THREAD

**Issue by victortm** [mmaelicke/scikit-gstat#28]
Hi,

I would like to know if it is possible to plot the interpolation results over a map like google maps, bing maps,..etc:

![image](https://user-images.githubusercontent.com/10722495/74667059-ec588f00-51a2-11ea-934c-2bdd2f91ed41.png)

Instead of the graphs showed in the tutorial:

![image](https://user-images.githubusercontent.com/10722495/74667145-1447f280-51a3-11ea-945c-c5aba2fc8631.png)

I don't know if you tried it before. But if you did, could you please recommend me any package?

Thanks and best regards

**Comment by mmaelicke** [comment]
Hey,

Of course this is possible, although not related to scikit-gstat. I do things like this professionally, therefore please understand that I won't post a copy-and-paste solution here, as I try to make money with such implementations. 

Nevertheless, everything you need is available and I will give you some guidance in case you want to implement this yourself. Scikit-gstat will yield some 2d-numpy arrays containing the data. What you'll have to do, is georeferencing them. 
1. You need to specify the reference system the coordinates are in and define e.g. how big one cell 
  is in that system. The Python implementation of [GDAL](https://pcjericks.github.io/py-gdalogr-cookbook/) is a good starting point. [Rasterio](https://rasterio.readthedocs.io/en/latest/) is my 
  personal favorite.
2.  You will most likely use one of the two javascript libraries [openlayers](https://openlayers.org/) or [leaflet](https://leafletjs.com/) to present a basemap on a website. My clear favorite here is leaflet.
3. Remember to reproject the georeferenced raster image if necessary. Most basemap providers only serve images in transversal pseudo-mercartor projection. This can be done e.g. with [GDAL transform](https://gdal.org/programs/gdaltransform.html). There are way more possibilities, like pyproj, or you use [QGis](https://qgis.org/de/site/), or even leaflet can do this directly, somehow (never used that option).
4. How does the raster come into the map? Well, that depends on the backend. You can get out your javascript skills and hackily put the raster directly into the Layer or TileLayer object of leaflet (I think has the same names in openlayers). This is of course very static though. You can set up a Flask backend that serves geo-json, which gives you reasonable degrees of freedom. Or you setup a full installation of [Geoserver](http://geoserver.org/) and serve a WMS properly. 

I hope this helps you to get on track and as I said before: I do thinks like this (implementation and consulting) for living and feel free to contact me on my mail to get in touch.

**Comment by victortm** [comment]
Thank you so much again Mirko.

Best regards
