### ISSUE TITLE
Each lower bound must be strictly less than each upper bound.

### ISSUE THREAD

**Issue by mserouar** [mmaelicke/scikit-gstat#29]
Hello, I'm facing a problem using your method, I get the error written in the title when I try to use Variogram.

Should we have values different from 0, because the z column corresponds to variance ?

![hh](https://user-images.githubusercontent.com/57948061/75867452-f0251c00-5e06-11ea-9801-a8cfb63e09d6.JPG)

Like this where z(uα) is a variance.

Here is how data csv looks like:

```
       x    y             z
0     32   32      0.000000
1     64   32  12594.463706
2     96   32  14421.667099
3    128   32      0.000000
4    160   32      0.000000
..   ...  ...           ...
251  384  512      0.000000
252  416  512      0.000000
253  448  512      0.000000
254  480  512      0.000000
255  512  512      0.000000

[256 rows x 3 columns]
```
Here is the reproducible exemple: 

```
import numpy as np
import matplotlib.pyplot as plt
plt.style.use('ggplot')
from pprint import pprint
from skgstat import Variogram


import pandas as pd
data = pd.read_csv('path/sample.csv',sep=";")

V = Variogram(list(zip(data.x, data.y)), data.z, normalize=False, n_lags=8, maxlag=10)
V.plot()
```

**Comment by mserouar** [comment]
I used z values different from 0s, and still get the same issue

**Comment by mmaelicke** [comment]
Hey Mario,
Thanks for submitting the issue. Can you make the whole csv file available? 

With just the few lines shown  I cannot calculate a Variogram. It might origin from the fitting of the theoretical model to the data. The default ``fit_method='trf'``, which sets a bound for the variogram parameters. Try to switch to ``fit_method='lm'`` to see if the error still occurs. If it does, it originates from somewhere else.

Best
Mirko

**Comment by mmaelicke** [comment]
And btw, the z value is an observation value, not the variance of the observation. What it actually means will be determined by your application.

**Comment by mserouar** [comment]
In switching to ``` fit_method='lm' ```
I get this

With this error : shape mismatch: objects cannot be broadcast to a single shape

![image](https://user-images.githubusercontent.com/57948061/75869094-61fe6500-5e09-11ea-8528-0b1e42fe63f5.png)

**Comment by mmaelicke** [comment]
Ok, just realizing that you might have misused the ``maxlag`` parameter. This is the documentation of it:
![image](https://user-images.githubusercontent.com/2826034/75868878-059b4580-5e09-11ea-8fab-35fce25188a6.png)
That means, in your case with ``maxlag=10``, you are giving the maximum lag distance itself in the units of your coordinate system. There are no axes on your image posted, but from the few coordinates I can tell, that no of these coordinates would be inside of ``maxlag``. 

Therefore I think that ``Variogram.experimental`` only contains NaN values, right? In that case, the Error is thrown by matplotlib when trying to set the axes limits for plotting. 

Last thing: It would be most helpful to post the error traceback as well, next time. The message is fine, but usually, I also need to know where it comes from...

Maybe you wanted to use ``maxlag=100``? 
Thanks.

**Comment by mserouar** [comment]
![image](https://user-images.githubusercontent.com/57948061/75869604-17c9b380-5e0a-11ea-89a6-515e4f8dbae7.png)

Thta's much better, thanks. 
However I have a 16x16 image, is maxlag=100 not too much ?

**Comment by mmaelicke** [comment]
Perfect. Maybe, look at your coordinates. the first is ``(32, 32)`` and the second ``(64, 32)``. Their distance is 
sqrt((32 - 32)**2 + (62 -32)**2) which is sqrt(1024) = 32, right? 

So, 10 is definitely too low. You can also set ``maxlag=None`` if you don't want to use it at all.  All ``maxlag`` does, is to exclude point pairs from the calculation at distances where you do not expect a statistical dependence anyway. In some textbooks you find hints like 'use half the maximum distance', which would correspond to ``maxlag=0.5`` or 'use the median of all distances' which would correspond to ``maxlag='median'``.

Hope this helps and will close the issue then.
Thanks
