### ISSUE TITLE
Nugget computation when normalize=True

### ISSUE THREAD

**Issue by estebanag** [mmaelicke/scikit-gstat#3]
In [this line](https://github.com/mmaelicke/scikit-gstat/blob/master/skgstat/Variogram.py#L553), shouldn't `cof[-1]` be multiplied by `maxvar` as well? Like so:
```python
nugget=cof[-1] * maxvar if self.use_nugget else 0
```

**Comment by mmaelicke** [comment]
Yes, absolutely. Changed it in 246255da4b3ff567f3d5c6bf49951d632d8e84c2.
Thanks!
