### ISSUE TITLE
basic installation

### ISSUE THREAD

**Issue by WesleyTheGeolien** [mmaelicke/scikit-gstat#31]
Hey,

More of a heads up than anything else, I went with the _default_ insatllation `pip install scikit-gstat` on Windows64 and shapely has some known problems not being able to get the `geos_c.dll` I think I read you can get around it by install OSgeo but running `conda install shapely` does the trick as well

**Comment by mmaelicke** [comment]
Hey Wesley,

Thanks for that note. Same applies to numpy installation via pip, which happens to fail from time to time in case some visual studio runtimes were not available. That reminds me, that I wanted to place a notice on this on the README.md. 

Did I get you right, that this is a note on installation issues, or did I overlook a question?

Best,

Mirko

**Comment by WesleyTheGeolien** [comment]
Hey,

Yeah just some installation mishaps nothing big though :) 

Hmmm I must have been lucky I didn't get the numpy problem!

**Comment by mmaelicke** [comment]
I finally updated the Readme and placed a not there. Therefore I will close this issue.
