### ISSUE TITLE
Ordinary Krigin Example and arguments

### ISSUE THREAD

**Issue by NikhilMunna** [mmaelicke/scikit-gstat#37]
Could you provide an example of ordinary kriging and what arguments it takes

**Comment by mmaelicke** [comment]
Hey,

Here goes the example: https://mmaelicke.github.io/scikit-gstat/userguide/kriging.html#example 
Here another one: https://mmaelicke.github.io/scikit-gstat/tutorials/01_getting_started.html

And there the possible arguments: https://mmaelicke.github.io/scikit-gstat/reference/kriging.html

If you you have more specific questions, do not hesitate to ask
Best,
Mirko
