### ISSUE TITLE
Area-to-point Kriging

### ISSUE THREAD

**Issue by Jing25** [mmaelicke/scikit-gstat#38]
I'm new to this. Does this library support ATPK?

**Comment by mmaelicke** [comment]
Dear Jing,
I am not familiar with area-to-point kriging. From what I know, the basic idea is to use areal information to predict at an unobserved location. For this to happen one would need a covariance function between point observations and the areal information. scikit-gstat does not implement a variogram model, that accounts for this kind of covariance. However, extending the builtin models is quite easy, so if there are no further limitations, that I am not aware of, that could be a possible road to take?

Also note, that scikit-gstat has only an OrdinaryKriging implementation and the [pykrige](https://github.com/GeoStat-Framework/PyKrige) interface is very experimental. Maybe [gstools](https://github.com/GeoStat-Framework/gstools), which integrades much better with pykrige, is a possible alternative.

Best Mirko

**Comment by Jing25** [comment]
Hi Mirko, 

Thank you for the explanation. I played a bit with pykrige. Your implementations and documents are more straightforward and easy to use for me. I personally prefer this one although .. I have some issue on using it..

Best,
Jing
