### ISSUE TITLE
Posibilidad de implementar ejemplos

### ISSUE THREAD

**Issue by potier97** [mmaelicke/scikit-gstat#42]
Hola, estoy intentando trabajar con scikit-gstat, por cierto, es genial tu librería, pero, no entiendo en parte como implementarlo para un simple ejercicio, entiendo los fundamentos teoricos, pero simpre me falla al crear uno, seri genial si pudiesen integrar un seccion de eejmplos en tu libreria.

Te cuento que lo estoy implementando  una red iot que adquiere distintas variables ambientales, quiero graficar la variable de la temperatura, tengo los datos tomados con la coordenada y el dato de la variable, en total son solo 5 nodos que nos entregan esa información, estan distribuidos en un espacio cerrado de 5x5 metros, pero no logro poder graficarlos, podrias instruirnos con un ejemplo. Gracias

Gracias por tu tiempo

**Comment by mmaelicke** [comment]
Sorry man, I don't speak Spanish. What I get from google translator is that you need examples.

Here is the [Getting Started Guide](https://mmaelicke.github.io/scikit-gstat/getting_started.html)

Here is a quite extensive part about Variograms: https://mmaelicke.github.io/scikit-gstat/userguide/variogram.html
The same for Kriging: https://mmaelicke.github.io/scikit-gstat/userguide/kriging.html

And if you need some more technical guidance for fitting, maybe these technical notes are helpful: https://mmaelicke.github.io/scikit-gstat/technical/fitting.html

Maybe I can help better, if you first ask in English and second give an data example that you are struggling to use.

Finally, if I got your last paragraph right, you are trying to interpolate from just 5 points? Then my advice would be, that geostatistics are the wrong tool. 
Finally, I am not sure if you really need an interpolation of temperature in a room of 5x5 meters. I am nor sure if there is any device out there with uncertainty margins smaller than the differences you are recording.

Examples should be provided therefore I'll close the issue, if I got you wrong somehow, feel free to re-open the issue anytime.
Best
Mirko
