### ISSUE TITLE
Rename dist_func

### ISSUE THREAD

**Issue by mmaelicke** [mmaelicke/scikit-gstat#46]
As the `Variogram.dist_func` is storing only the user input since #45 and the actual callable distance function is now `Variogram._dist_func_wrapper` (thanks to @redhog), I am wondering if we can't come up with a better naming, because now it is a bit confusing. maybe `dist_func` should be `dist_func_name` and `_dist_func_wrapper` maybe `dist_function` ? 
@redhog, comments, ideas?

**Comment by redhog** [comment]
Sounds good to me :)
