### ISSUE TITLE
Sampling of point pairs

### ISSUE THREAD

**Issue by redhog** [mmaelicke/scikit-gstat#48]
Sample the point pairs randomly to speed up handling of big datasets. Method:

* Repeat
  * Sample datapoints
  * Build & filter pairs
  * Append pairs to total list of pairs

This way, it would even be possible to include all points (but not all pairs) while keeping the complexity at O(N) rather than O(N^2).

**Comment by mmaelicke** [comment]
What do you think is the number of points, at which this does really make a difference? 

The `Variogram` class is building an array, like the `pdist` function does. It's an array of `(N*2 / 2) - N` lengh for N points, like the upper triangle of a `NxN` shaped matrix containing all combinations. 
I am not so sure which parts of the class assume the array to be of that shape. If I get you right, you would randomly choose pairs over and over again, until each point is somehow incorporated, but stop before the array grows too large. I see the advantage if it is feasible to add this for large datasets **only**. For smaller ones, where the computation times are small anyway, I think it's better to be 'deterministic' with a variogram that yields the same values on every run.

**Comment by redhog** [comment]
I agree about small datasets. Not sure at what size it starts to matter - possibly only really large datasets.

Right now I do a single sample before I run the directional variogram (outside of the class), but that obviously makes the results a bit unstable. I started doing this back when I was using the code using shapely - and even with the sampling my dataset took over night to compute. With the new code, it's < 30s for a 20% sample...

My idea would be to do this multiple times and average the results, "outside" of the pdist call, so that for each subsample you still build the (N*2 / 2) - N pdist-like array, but with N = sample size rather than dataset size...

**Comment by mmaelicke** [comment]
Ok, that shouldn't be too complicated. If I recall my own code correct, the only function filling the array is `_calc_distances`, which is implementing the new wrapper you added.

So we could add a check here:
https://github.com/mmaelicke/scikit-gstat/blob/e09a65047bbd5430e55d26c967be4ddcfe41849e/skgstat/Variogram.py#L1015

or more precisely in front of this line:
https://github.com/mmaelicke/scikit-gstat/blob/e09a65047bbd5430e55d26c967be4ddcfe41849e/skgstat/Variogram.py#L1025

to implement something like:

```
threshold = 10000 # maybe the user can set this
if len(self._X) > threshold:
    # _x is a referebce to self._X; or _X with a stacked 0 array if _X.dim == 1
    _x = self._new_sampling_method(_x)

# now run the old line
self._dist = self._dist_func_wrapper(_x)
```

Did I get you right?

**Comment by MuellerSeb** [comment]
I can confirm, that the number of point pairs is crucial.
[GSTools](https://github.com/GeoStat-Framework/GSTools) provides a sample size parameter for variogram estimation. Maybe you could have a glimpse there.

**Comment by redhog** [comment]
There is another possible point pair culling that can be done: We could set a max-dist, and only consider pairs where the distance is shorter than max-dist. This could possibly be sped up even more by comparing x and y distance separately.

There is a similar issue in kriging btw.

My very non-systematic experimentation shows that when number of points > a couple of thousands, performance goes to absolute crap.

**Comment by mmaelicke** [comment]
Yeah, I have never used the code with more than a few hundred points, and performance was usually not an issue. Feel free to propose a roadmap. I myself might not find the time to implement something this year, I'm busy with other stuff.

**Comment by redhog** [comment]
No worries :)

My roadmap / the roadmap of my employer is to optimize the situation where your area is much larger than the effective range, and where you know this in advance (and possibly know an upper bound on the effective range too), but I'll start at the kriging end, because that's where the most low-hanging fruit is: https://github.com/mmaelicke/scikit-gstat/issues/58

**Comment by redhog** [comment]
Possible implementation:

Using a `MetricSpacePair` with two different random point samples instead of a `MetricSpace`. It would need to be wrapped in something that makes the output of `dists()` square (and even more sparse). If this can be achieved, it would not require any changes to `Variogram`.
