### ISSUE TITLE
This can never have worked? Triangle calculation...

### ISSUE THREAD

**Issue by redhog** [mmaelicke/scikit-gstat#51]
While debugging why I get slightly different results with the new directional models, I came across this:

![image](https://user-images.githubusercontent.com/104229/94062516-13d1a300-fde7-11ea-984a-e23af64bb605.png)

The green triangle is generated using the old code, while the black dots and blue lines are added using my angle calculation. This is for a point that the old code considers "inside" the tolerance, and the new code outside. So what's going on? I added the red lines, calculated using

    a = np.radians(DV.tolerance)
    ax.plot([0, dists[x] * np.cos(a)],
           [0, dists[x] * np.sin(a)], color="red")
    ax.plot([0, dists[x] * np.cos(-a)],
           [0, dists[x] * np.sin(-a)], color="red")

(I first tried half the tolerance, and that gives an even narrower angle, obviously). Why don't they agree with the green ones?

So I looked at the _compass function, more specifically this line:
https://github.com/mmaelicke/scikit-gstat/blob/master/skgstat/DirectionalVariogram.py#L760

This can't be correct, can it? It should read `r = xmax / cos(a)`, not `r = xmax / a`, right?

**Comment by redhog** [comment]
Update: Changing this to 

    r = xmax / np.cos(a)

makes the new and old methods agree 100% about DV._direction_mask()

**Comment by mmaelicke** [comment]
You are absolutely right: 

https://github.com/mmaelicke/scikit-gstat/blob/e09a65047bbd5430e55d26c967be4ddcfe41849e/skgstat/DirectionalVariogram.py#L738

In the docstring, I am stating that *r = xmax / cos(a)* with *a = alpha / 2*, but in the implementation I omitted the cos. That means, the unittests test against a wrong result. Sorry, I was really in a hurry at that time and didn't double check the unittest results before implementing them.

**Comment by redhog** [comment]
Awesome to have that figured out. I'll make a PR with a fix to that and the unittests, and then we can check the direction PR using those fixed unittests...
