### ISSUE TITLE
Nugget effect

### ISSUE THREAD

**Issue by guanjundeya** [mmaelicke/scikit-gstat#56]
I tried different data set and set `use_nugget = True`, but turned out estimated nugget effect always being 0. Any idea? Thanks.

**Comment by mmaelicke** [comment]
Hey,
Well, it would be most helpful to give me a minimum example of what you did and how your data looks like. Is the nugget always exactly 0 or just close to 0?

Technically, estimating a nugget works fine, as far as I can tell. Consider an example of normal distributed values, which will very likely show a nugget effct:

```Python
import skgstat as skg
import numpy as np
import matplotlib.pyplot as plt

np.random.seed(42)
c = np.random.normal(0,1,size=(20,2))
np.random.seed(42)
v = np.random.normal(0,2,20)

# one with nugget one without
V1 = skg.Variogram(c,v,normalize=False, use_nugget=False, n_lags=6)
V2 = skg.Variogram(c,v,normalize=False, use_nugget=True, n_lags=6)

fig, ax = plt.subplots(1,2,sharey=True)
V1.plot(axes=ax[0], hist=False)
V2.plot(axes=ax[1], hist=False)
ax[0].set_title('use_nugget=False')
ax[1].set_title('use_nugget=True')
```
![image](https://user-images.githubusercontent.com/2826034/98208758-238feb80-1f3e-11eb-816d-4082ef06f296.png)

**Comment by mmaelicke** [comment]
Will close this issue due to inactivity. Feel free to re-open if there are still questions.
