### ISSUE TITLE
Optimize distance function in kriging

### ISSUE THREAD

**Issue by redhog** [mmaelicke/scikit-gstat#58]
When krigin, a distance function is called for each point to calculate its distance to every point in the variogrammed dataset. This might be necessary if the use has supplied their own distance metric, but if it's one of the built in scipy, we can use scipy.spatial.distance.cdist on all points instead, and if it's euclidean, we can even use scipy.spatial.cKDTree, see ttps://iliauk.wordpress.com/2016/02/16/millions-of-distances-high-performance-python/ , which would automatically cull the points farther away than the range without actually doing a distance calculation on them.

- [X] Optimize [observation selection](https://github.com/emerald-geomodelling/upstream-scikit-gstat/blob/2faae465b9a42c2b00e302157c44954bc510713c/skgstat/Kriging.py#L380)
- [x] Optimize [kriging equation creation](https://github.com/emerald-geomodelling/upstream-scikit-gstat/blob/2faae465b9a42c2b00e302157c44954bc510713c/skgstat/Kriging.py#L396)

**Comment by mmaelicke** [comment]
I commented in #60 ...

**Comment by mmaelicke** [comment]
@redhog was this resolved by #60 ?

**Comment by redhog** [comment]
Only half-way. I added the two subtasks above...

**Comment by mmaelicke** [comment]
OK, great! Then I'll leave this open.

**Comment by redhog** [comment]
The idea I have is to generate a pdist matrix for _all_ observation points at the top, then select the sub-matrix for the nearby points instead of calling self.dist().
This might even be worth allowing "short circuit" for between Kriging and Variogram, that is, allow you to send in a distance matrix alongside with coordinates and values.

**Comment by redhog** [comment]
As far as I can see this is solved in https://github.com/mmaelicke/scikit-gstat/blob/master/skgstat/Kriging.py#L415
