### ISSUE TITLE
GStools interface bug

### ISSUE THREAD

**Issue by MuellerSeb** [mmaelicke/scikit-gstat#78]
https://github.com/mmaelicke/scikit-gstat/blob/664eb89a8d578ff27c7e820e2edbd34ed3ee3ac1/skgstat/interfaces/gstools.py#L44

The referenced line is most probably not doing anything useful, since the overridden `variogram` method doesn't make use of the internal attributes `var`, `nugget`, `len_scale` or any aditional hyperparameter.

This should be fixed by a better conversion function in the future.

**Comment by mmaelicke** [comment]
I am not sure if the interface is doing something useful at all... :)
I think we can completely replace this with a new interface. I give you a call in the next couple of days. 
On mid-term, I want to replace the whole `interface` submodule anyway. 

I'll keep this open as a reminder and to build up some pressure on myself.

**Comment by MuellerSeb** [comment]
Cross-referencing this issue here: https://github.com/GeoStat-Framework/GSTools/issues/92
