### ISSUE TITLE
Export coordinates as cond_pos

### ISSUE THREAD

**Issue by mmaelicke** [mmaelicke/scikit-gstat#90]
I wrapped my whole day around the skgstat - gstools interface today. I tried to use the `gstools.krige.Krige` with one of `skgstat.Variogram`.  This is what happened:
![image](https://user-images.githubusercontent.com/2826034/115252947-384aef00-a12c-11eb-9cfb-4658fd5adb26.png)
 
The sciki-gstat Ordinary Kriging worked just well.  After hours I finally found the source of error, which was as usually sitting in front of the computer. This is the code I used:
```Python
model = panvar.to_gstools()    # panvar is a Variogram
cond_pos = panvar.coordinates    #  <-- this is the mistake
cond_vals = panvar.values
```

The `Variogram.coordinates` returns a numpy array of shape `(n_obs, dim)`, while `Krige` wants a list of length `n_obs` for each `dim`.
Finally, the solution is simply:

```Python
x, y = zip(*panvar.coordinates)
gs.krige.Ordinary(model, [x, y], panvar.values)
```

I feel like this will not be the last time that I do this wrong. Possibly, other users of scikit-gstat might run into the same trap. I will add a note into the docs, but I think I have to be more proactive here.
My suggestion is to add a new function to `Variogram`, similar to `get_empirical` to return `cond_pos` and `cond_vals`. @MuellerSeb what do you think? Any other thought, suggestion or pathway, before I get started?

**Comment by MuellerSeb** [comment]
Yeah, this is always a problem. `cond_pos = panvar.coordinates.T` is my preferred way of doing this.
I don't know if this really needs a new interface of just a good documentation!
