### ISSUE TITLE
Documentation of MetricSpace.dists and MetricSpace.tree

### ISSUE THREAD

**Issue by redhog** [mmaelicke/scikit-gstat#91]
I noticed that https://mmaelicke.github.io/scikit-gstat/reference/metric_space.html#skgstat.MetricSpace is missing documentation for the properties...

I assume the docs are auto-generated from docstrings etc, so:

How do I add documentation for properties? Just docstrings inside the @property def?

**Comment by mmaelicke** [comment]
Yeah, exactly. just like any other function. You could i.e. refer to the `Variogram.bins` property. Its docstring compiles to https://mmaelicke.github.io/scikit-gstat/reference/variogram.html#skgstat.Variogram.bins

 What I am also struggling with is how to document the property setter in a clean way. Usually, I make the setter call another instance method (i.e. `set_estimator_func`, `set_bin_func` and so on). Then, these function can be referenced in the 
```
See Also
------------
Variogram.set_bin_func
```
section.

If that is really the best way to document, I am not so sure. At least we have documentation ;)

**Comment by redhog** [comment]
I think I'd just go for documenting both setter and getter in the same docstring?

**Comment by mmaelicke** [comment]
yeah. That's fine. 
BTW. There is also the 'Userguide' Milestone that should collect issues that point to missing documentation. You can place anything in there, that you spot.
If you do not assign yourself to these kind of issues, I will document and close them whenever I am too bored...
