### ISSUE TITLE
Is cokriging available in the current implementation? 

### ISSUE THREAD

**Issue by flydream0428** [mmaelicke/scikit-gstat#98]
Is cokriging available in the current implementation? Is there a plan to add this if not?

**Comment by mmaelicke** [comment]
Hey there,

No, unfortunately not. In fact, `scikit-gstat` only implements ordinary kriging. But there is an interface to `gstools` and `pykrige` and both have way more kriging algorithms available. I.e.:

```Python
import skgstat as skg

vario = skg.Variogram(coords, values, ...)
krige = vario.to_gs_krige(**args)

# i.e. use a structured grid
x = y = range(100)
field, sigma = krige.structured([x,y])
```
The `**args` part is passed down to gstools, refer to [their docs](https://geostat-framework.readthedocs.io/projects/gstools/en/latest/generated/gstools.krige.Krige.html) for available parameters (`model, cond_pos, cond_val` are already set by `Variogram`)

Gstools does not have cokriging as far as I know, but external drift kriging which might be an option as well?
 
I'll close this issue, if there are further questions, feel free to open again
